### PR TITLE
fix: download core client version appropriate for the installer

### LINKED ISSUE #300: Installer should download latest compatible CLI version
The FuseML installer currently downloads the latest available CLI binary release. This behavior doesn't cover the following cases:

- older installer (e.g. v0.2.1) installs older core sever release (v0.2.1) and downloads newer and possibly incompatible CLI (e.g. v0.3.0). This can result in CLI failures, as the 0.3 CLI isn't guaranteed to be backwards compatible.
- installer should warn/fail if a compatible CLI isn't available for download
- the fuseml/fuseml CI running on the release tags ignores the fuseml CLI downloaded by the installer and instead is re-compiling the CLI from the fuseml/fuseml-core code in the same branch. This doesn't reflect the end-user behavior and should be changed to use the installer downloaded CLI. To allow for periodic, pre-release testing, however, it should only do that for release tags.

We should assume that the CLI and installer are not release-locked and instead semantic versioning rules are followed. For alpha releases, this means that patch CLI releases are backwards compatible with server/installer releases in the same minor release (for example a v0.3.0 installer and server version are compatible with a v0.3.1 CLI and vice-versa).

### PR DESCRIPTION
**Pull request by jsuchome**
When downloading the core client binary, check the installer version
and take the client version that is expected to be compatible, i.e.
it is the latest one that only differs in patch version.

closes #300

I've also changed the UI a little bit, this is how it looks for released version:
```bash
🚢 Downloading command line client...
🚢 For installer version v0.2, downloading client version v0.2.1

✔️  FuseML command line client saved as /home/jsuchome/kubernetes/fuseml/fuseml.

    It is recommended to copy it to the location within your PATH (e.g. /usr/local/bin).
```
and for dev version:
```bash
🚢 Downloading command line client...
🚢 Downloading latest stable version of the client

✔️  FuseML command line client saved as /home/jsuchome/kubernetes/fuseml/fuseml.

    It is recommended to copy it to the location within your PATH (e.g. /usr/local/bin).
```

Better to show the screenshot, to see different colors:

fuseml-install-cli

### CODE REVIEW

File: paas/install_cli.go [hunk 1]
```diff
@@ -1,35 +1,115 @@
...
+
+	releasesFile := "releases.json"
+	if err := helpers.DownloadFile(coreAPIURL, releasesFile, tmpDir); err != nil {
+		return "", err
+	}
+
+	data, err := os.ReadFile(filepath.Join(tmpDir, releasesFile))
+	if err != nil {
+		return "", errors.Wrap(err, "failed to read description file")
+	}
```
Comment (stefannica) [inline paas/install_cli.go:49]: It feels like you go to a lot of trouble here just to read the releases JSON manifest. You don't actually need to download it and then read it from disk, you can just read it from the HTTP response body.

**Review by stefannica — APPROVED** [review]
One nit concerning how you retrieve the JSON release manifest from github, but otherwise looks good.

File: paas/install_cli.go (hunk 1 above)
Comment (jsuchome) [reply paas/install_cli.go:49]: You are right, of course. I just started with existing download method and then just read a file.

I admit it's unnecessary, though I would not agree it's "a lot of trouble". I guess I could change it though

**Review by stefannica — APPROVED** [review]
